### PR TITLE
#3 Project API - Create project

### LINKED ISSUE #3: Project API - Create project
### AC

- endpoint is created
- logic is implemented
- logic is covered by unit tests (controller, services) for negative and positive scenarios

#### Request

Path: `api/v1/project`  
Method: `POST`  
**Headers:**

-  `Content-Type: application/json`
- `X-ACCOUNT-ID: uuid` - mandatory, someone who performs the call(later we well implement the source of this id. now lets use the random)

**Body:**
- `name` - mandatory
- `description` - optional
-  `status` - optional
``` json
{
	"name": "Example project"
}
```

#### Response

Status `CREATED` - successfully performed operation

**Body:**

- `ok` - true if success, false in case of error
- `result`
    - `id`
    - `ownerId`
    - `name`
    - `description`
    - `status`
- `errorMessage` - short error description

``` json
{
	"ok": true,
	"result": {
		"id": 1000,
	    "name": "Example project",
	    "ownerId": "cf908f33-b46a-459a-925c-e7439582e6d6",
	    "description": "Some example of description",
	    "status": "active"
	}
}
```
----
Status `BAD REQUEST` - data is invalid
``` json
{
	"ok": false,
	"errorMessage": "Missed 'name' property"
}
```
----
Status `INTERNAL SERVER ERROR` - other errors
``` json
{
	"ok": false,
	"errorMessage": "Internal server error"
}
```
----
### Implementation details

- `status` - if missed default value is `active`
- `ownerId` - take value from `X-ACCOUNT-ID`
- persist request data to the `roll.project` db table
- create a common response type that wraps common response attributes: `ok`, `result`, `errorMessage`
- configure global exception handler to provide consistent response

### PR DESCRIPTION
**Pull request by hasya1993**

### CODE REVIEW

File: app/src/main/java/com/metrics_board/app/controller/roll/ProjectController.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+import java.util.UUID;
+
+@RestController
+@RequiredArgsConstructor
+public class ProjectController {
+    private final ProjectService projectService;
+
+    @PostMapping("/api/v1/project")
+    public ResponseEntity<ApiResponse<ProjectResponse>> createProject(
+            @RequestHeader("X-ACCOUNT-ID") UUID ownerId,
```
Comment (martynovskyi) [inline app/src/main/java/com/metrics_board/app/controller/roll/ProjectController.java:25]: Header `X-ACCOUNT-ID` also mandatory

File: app/src/main/java/com/metrics_board/app/controller/roll/ProjectController.java [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+            @RequestBody @Validated ProjectRequest request) {
+        Project createdProject = projectService.createProject(ownerId, request);
+        ProjectResponse projectResponse = projectService.createProjectResponse(createdProject);
```
Comment (martynovskyi) [inline app/src/main/java/com/metrics_board/app/controller/roll/ProjectController.java]: Do this by single `ProjectService` call

File: app/src/main/java/com/metrics_board/app/controller/roll/ProjectController.java [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+
+        return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.<ProjectResponse>builder()
```
Comment (martynovskyi) [inline app/src/main/java/com/metrics_board/app/controller/roll/ProjectController.java]: minor, create short static method
`ApiResponse.success(T something)`

File: app/src/main/java/com/metrics_board/app/dto/roll/ProjectRequest.java [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+@Getter
+@Setter
+@Builder
+@NoArgsConstructor
+@AllArgsConstructor
+public class ProjectRequest {
+    @NotEmpty(message = "Missing 'name' property")
+    private String name;
+    private String description;
+    @Pattern(regexp = "^(active|suspended|archived)$", message = "Missing 'status' property")
```
Comment (martynovskyi) [inline app/src/main/java/com/metrics_board/app/dto/roll/ProjectRequest.java]: `Unexpected 'status' value`

File: app/src/main/java/com/metrics_board/app/exeption/GlobalExceptionHandler.java [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+import com.metrics_board.app.dto.ApiResponse;
+import org.springframework.http.ResponseEntity;
+import org.springframework.web.bind.MethodArgumentNotValidException;
+import org.springframework.web.bind.annotation.ControllerAdvice;
+import org.springframework.web.bind.annotation.ExceptionHandler;
+
+import java.util.Objects;
+
+@ControllerAdvice
+public class GlobalExceptionHandler {
```
Comment (martynovskyi) [inline app/src/main/java/com/metrics_board/app/exeption/GlobalExceptionHandler.java:18]: Try with `ApiResponse<Void>`

File: app/src/main/java/com/metrics_board/app/exeption/GlobalExceptionHandler.java [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+                .build());
+    }
+
+    @ExceptionHandler(MethodArgumentNotValidException.class)
+    public ResponseEntity<Object> handleValidationExceptions(MethodArgumentNotValidException e) {
+        return ResponseEntity.badRequest().body(ApiResponse.builder()
+                .ok(false)
+                .errorMessage(Objects.requireNonNull(e.getBindingResult().getFieldError()).getDefaultMessage())
+                .build());
+    }
```
Comment (martynovskyi) [inline app/src/main/java/com/metrics_board/app/exeption/GlobalExceptionHandler.java:56]: minor, create a short static method
ApiResponse.error(T something)

File: app/src/main/java/com/metrics_board/app/exeption/GlobalExceptionHandler.java [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+    public ResponseEntity<ApiResponse<Object>> handleException(Exception e) {
+        return ResponseEntity.internalServerError().body(ApiResponse.builder()
+                .ok(false)
+                .errorMessage("Internal server error")
+                .build());
+    }
+
+    @ExceptionHandler(MethodArgumentNotValidException.class)
+    public ResponseEntity<Object> handleValidationExceptions(MethodArgumentNotValidException e) {
+        return ResponseEntity.badRequest().body(ApiResponse.builder()
```
Comment (martynovskyi) [inline app/src/main/java/com/metrics_board/app/exeption/GlobalExceptionHandler.java]: need to avoid unsafe operations in exception handler!
```
        String message = e.getFieldErrors().stream()
                .findFirst()
                .map(FieldError::getDefaultMessage)
                .orElse("Some property invalid");
        
        return ResponseEntity.badRequest().body(ApiResponse.builder()
                .ok(false)
                .errorMessage(message)
                .build());
```

File: app/src/main/java/com/metrics_board/app/exeption/GlobalExceptionHandler.java [hunk 8]
```diff
@@ -0,0 +1,28 @@
...
+import org.springframework.web.bind.MethodArgumentNotValidException;
+import org.springframework.web.bind.annotation.ControllerAdvice;
+import org.springframework.web.bind.annotation.ExceptionHandler;
+
+import java.util.Objects;
+
+@ControllerAdvice
+public class GlobalExceptionHandler {
+    @ExceptionHandler(Exception.class)
+    public ResponseEntity<ApiResponse<Object>> handleException(Exception e) {
```
Comment (martynovskyi) [inline app/src/main/java/com/metrics_board/app/exeption/GlobalExceptionHandler.java]: Please add logging

File: app/src/main/java/com/metrics_board/app/service/roll/ProjectService.java [hunk 9]
```diff
@@ -0,0 +1,38 @@
...
+@RequiredArgsConstructor
+public class ProjectService {
+    private final ProjectRepository projectRepository;
+
+    public Project createProject(UUID ownerId, ProjectRequest request) {
+        Project project = Project.builder()
+                .ownerId(ownerId)
+                .name(request.getName())
+                .description(request.getDescription())
+                .status(request.getStatus() != null ? ProjectStatus.valueOf(request.getStatus().toUpperCase()) : ProjectStatus.ACTIVE)
```
Comment (martynovskyi) [inline app/src/main/java/com/metrics_board/app/service/roll/ProjectService.java]: Try to use `ProjectStatus.of(String s)`

**Review by martynovskyi — CHANGES_REQUESTED** [review]

File: app/src/test/java/com/metrics_board/app/controller/roll/ProjectControllerTest.java [hunk 10]
```diff
@@ -0,0 +1,172 @@
...
+                                }
+                                """))
+                .andExpectAll(
+                        status().isBadRequest(),
+                        content().contentType(MediaType.APPLICATION_JSON),
+                        jsonPath("$.ok").value(false),
+                        jsonPath("$.errorMessage").value("Missing 'name' property")
+                );
+
+        this.mockMvc.perform(post("/api/v1/project")
```
Comment (martynovskyi) [inline app/src/test/java/com/metrics_board/app/controller/roll/ProjectControllerTest.java:83]: This needs to be 2 tests or one parameterized test

File: app/src/test/java/com/metrics_board/app/controller/roll/ProjectControllerTest.java [hunk 11]
```diff
@@ -0,0 +1,172 @@
...
+                                "name" : "Test"
+                                }
+                                """))
+                .andExpectAll(
+                        status().isInternalServerError(),
+                        content().contentType(MediaType.APPLICATION_JSON),
+                        jsonPath("$.ok").value(false),
+                        jsonPath("$.errorMessage").value("Internal server error")
+                );
+    }
```
Comment (martynovskyi) [inline app/src/test/java/com/metrics_board/app/controller/roll/ProjectControllerTest.java:193]: I don't see a test where no request body

File: app/src/main/java/com/metrics_board/app/exeption/GlobalExceptionHandler.java [hunk 12]
```diff
@@ -0,0 +1,51 @@
...
+
+    @ExceptionHandler(MethodArgumentTypeMismatchException.class)
+    public ResponseEntity<ApiResponse<Void>> MethodArgumentTypeMismatchException(MethodArgumentTypeMismatchException e) {
+        if (e.getParameter().getParameterType() == UUID.class) {
+            return badRequest("'X-ACCOUNT-ID' is invalid");
+        }
+        return badRequest("Some property is invalid");
+    }
+
+    private ResponseEntity<ApiResponse<Void>> badRequest(String message) {
```
Comment (martynovskyi) [inline app/src/main/java/com/metrics_board/app/exeption/GlobalExceptionHandler.java:54]: 👍

File: app/src/test/java/com/metrics_board/app/service/roll/ProjectServiceTest.java [hunk 13]
```diff
@@ -0,0 +1,47 @@
...
+@ExtendWith(MockitoExtension.class)
+public class ProjectServiceTest {
+    @Mock
+    ProjectRepository projectRepository;
+
+    @InjectMocks
+    ProjectService projectService;
+
+    @Test
+    public void testCreateProject() {
```
Comment (martynovskyi) [inline app/src/test/java/com/metrics_board/app/service/roll/ProjectServiceTest.java:28]: 👍

**Review by martynovskyi — APPROVED** [review]
